<#import "parts/login_form.ftlh" as form>
<#import "parts/navbar.ftlh" as navbar>
<#import "parts/header.ftlh" as header>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add subject</title>
    <@header.all/>
    <link href="css/pagination.css" rel="stylesheet">
</head>
<body>
<@navbar.navbar role = "guest"/>

<p></p>

<div class="col-md-8 col-md-offset-4">
    <h4>Add subject</h4>
</div>



</body>
</html>